### ISSUE TITLE
Add Technologies Link to Navbar

### ISSUE THREAD

**Issue by taiwotkj** [massenergize/massenergize-campaigns#159]
Aimee, a MassE campaign user logged in on a campaigns page and thinks having a link to the technologies page is essential on the navbar. 

**Scenarios:**
1. **GIVEN** a MassE campaign user viewing a campaign page
WHEN the user logs in to the campaign home page
THEN they should be able to see _Technologies_ as part of the nav links 
AND the _Technologies_ link should be in-between _Home_ and _Coaches_ link. 

2. **GIVEN** a MassE campaign user viewing a campaign page
WHEN the user clicks on _Technologies_ on the navbar
THEN they should be taken to the technologies page or section. 

**Acceptance Criteria:**
Users can see _Technologies_ as part of navbar links.
Users can click on _Technologies_ and it redirects them to the correct section or page. 

**Additional notes:** remove two logos to make room to add technologies after _Home_ link and before _Coaches_ link. 

**Technical Considerations:**
N/A

Images and UX

**Comment by abdullai-t** [comment]
@taiwotkj and @archx3, this is a backend task.

**Comment by archx3** [comment]
Alright.
I'll edit the title and label accordingly and assign to you

**Comment by frimpongopoku** [comment]
@abdullai-t while you are in there, add `section=home` as a param to the home link.
